import avocat.act as act
from collections import defaultdict


def find_sol(out, err):
    """ find a solution tree for the given stderr/stdout """
    return database[err]
    #act.Choice(Q="which looks right?", choices=["abc", "xyz"])
    #return act.Tree()

database = defaultdict(
    lambda: act.Shell(act.Const(data="echo"), act.Const(data="autogenerated")),
    {
        "Assertion Error! Cats are bad programmers.\n":
            act.Shell(
                act.Const(data="echo"), 
                act.Const(data="cats are indeed bad programmers"), 
            ),
        "ls: cannot access 'thisdoesnotexist': No such file or directory\n":
            act.Shell(
                act.Const(data="echo"), 
                act.Const(data="you are an idiot"), 
            )
    }
)